
-- Seed data for the Rumbos Envios application

-- Insert sample clients
INSERT INTO public.clientes (id, nombre, apellido, direccion, telefono, email, notas, created_at) VALUES
('a1b2c3d4-e5f6-7890-1234-567890abcdef', 'Ana', 'García', 'Calle Falsa 123, Springfield', '+1 555 123 4567', 'ana.garcia@example.com', 'Cliente frecuente, prefiere entregas por la mañana.', NOW()),
('b2c3d4e5-f6a7-8901-2345-678901bcdef0', 'Carlos', 'Rodríguez', 'Avenida Siempreviva 742, Shelbyville', '+1 555 987 6543', 'carlos.rodriguez@example.com', NULL, NOW()),
('c3d4e5f6-a7b8-9012-3456-789012cdef0a', 'Laura', 'Martinez', 'Boulevard de los Sueños Rotos 45, Capital', '+54 911 2345 6789', 'laura.martinez@example.com', 'Dejar el paquete en recepción si no está.', NOW());

-- Insert sample shipments
-- Assuming Ana García's ID is 'a1b2c3d4-e5f6-7890-1234-567890abcdef'
INSERT INTO public.envios (id, cliente_id, nombre_cliente_temporal, client_location, package_size, package_weight, status, suggested_options, reasoning, created_at) VALUES
('d4e5f6a7-b8c9-0123-4567-890123def012', 'a1b2c3d4-e5f6-7890-1234-567890abcdef', NULL, 'Calle Falsa 123, Springfield', 'medium', 2.5, 'pending', NULL, NULL, NOW()),
('e5f6a7b8-c9d0-1234-5678-901234ef0123', NULL, 'Nuevo Cliente Temporal', 'Oficina Central, Microcentro', 'small', 0.8, 'suggested', '{"suggestedOptions": ["Moto Express", "Bicimensajería"], "reasoning": "Paquete pequeño y liviano para entrega rápida en zona céntrica."}'::json, 'Sugerencias basadas en tamaño y urgencia típica para la zona.', NOW());

-- You can add more INSERT statements here for other tables or more data.
-- Remember to use unique IDs if your schema enforces them.
-- For `created_at` or similar timestamp fields, `NOW()` is generally appropriate.
-- For JSON fields like `suggested_options`, ensure valid JSON syntax.
-- Example for suggested_options: '{"option1": "details", "option2": "details"}'::json
-- If your table has auto-incrementing IDs or UUIDs generated by default, you might omit them from the INSERT statement.
-- However, for seed data, explicitly setting IDs can be useful for predictability if other seed data depends on these IDs.
-- Always ensure data types match your table schema.
-- For example, package_weight is numeric, package_size is likely an enum or text.
-- Status fields should match predefined values if they are enums or have check constraints.

-- Note: If you have foreign key constraints, ensure the referenced data exists.
-- E.g., cliente_id in 'envios' must match an id in 'clientes'.
-- If using UUIDs for IDs, ensure they are unique or use uuid_generate_v4() if the extension is available and appropriate for your setup.
-- The provided UUIDs are for example purposes only.

